insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
]

insta/photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate
from django.conf.urls.static import static
from django.conf import settings


app_name = "photo"
#app_name 설정을 통해 namespace확보
#prevents url pattern이름 겹치는 것 with other apps

urlpatterns = [
	path("create/", PhotoCreate.as_view(), name = 'create'),
	path("delete/<int:pk>/", PhotoDelete.as_view(), name = 'delete'),
	path("update/<int:pk>/", PhotoUpdate.as_view(), name = 'update'),
	path("detail/<int:pk>/", PhotoDetail.as_view(), name = 'detail'),
	path("", PhotoList.as_view(), name = 'index'),
	#<int:pk> : 해당 작성에 대한 번호로 이동해야 상세 페이지 및 그 글 삭제/수정 가능..
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

insta/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Photo(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'user')
	#장고에서 구현하는 user 불러와서 photo를 fk로 연결
	text = models.TextField(blank=True)
	image = models.ImageField(upload_to = 'timeline_photo/%Y/%m/%d')
	#timeline_photo 폴더에 year, month, day 만들어서 사진 저장
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "text : " + self.text
		#admin 사이트 화면 표시 구현

	class Meta:
		ordering = ['-created']
		#ordering 정렬

	def get_absolute_url(self):
		return reverse('photo:detail', args = [self.id])
	#상세 페이지로 이동하도록 absolute_url 설정. view에서 return super나오면 absolute실행
	

insta/photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo
from django.contrib import messages
# Create your views here.

#class형 뷰의 generic view를 이용해서 구현
#ListView/CreateView/UpdateView/DeleteView/DetailView 구현

class PhotoList(ListView):
	model = Photo
	template_name_suffix = '_list'
	#PhotoList : 가장 메인에서 보여줄 Logic/model을 불러와서 데이터를 활용하것이라고 기제

class PhotoCreate(CreateView):
	model = Photo
	fields = ['text', 'image']
	template_name_suffix = '_create'
	success_url ='/'
	#PhotoCreate : 모델 생성할때 채워야할 필드확인, 연결된 템플릿 이름은 Photo_to_create
	#if success -> back to main page
	def form_valid(self, form):
		form.instance.author_id = self.request.user.author_id
		if form.is_valid():
			form.instance.save()
			return redirect('/')
		else:
			return self.render_to_response({'form': form})

class PhotoUpdate(UpdateView):
	model = Photo
	fields = ['text','image']
	template_name_suffix = '_update'
	success_url = '/'
	#photo update : similar to create

class PhotoDelete(DeleteView):
	model = Photo
	template_name_suffix = '_delete'
	success_url = '/'

class PhotoDetail(DetailView):
	model = Photo
	template_name_suffix = '_detail'

insta/photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            Fill Out Everything!!
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

insta/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="alert alert-primary" role="alert">
  Are you sure to delete {{object}}?
</div>

<form action="" method ="post">
    {% csrf_token%}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

insta/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" >
            <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text"> {{ object.text }} </p>
            </div>
            <ul class = "list-group list-group-flush">
                <li class = "list-group-item">Upload date : {{ object.created }}</li>
                <li class = "list-group-item">
                    {% load disqus_tags %}
                    <div class = "card-body">
                        {% disqus_show_comments %}
                    </div>

                </li>
            </ul>

            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">Edit</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">Delete</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

insta/photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class='container'>
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Upload Date : {{ object.created }}</li>
                    <li class="list-group-item">Edit Date : {{ object.updated }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">Comment</a>
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}" class="card-link">Edit</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">Delete</a>
                    {% endif%}
                </div>

            </div>
            {% endfor %}
        </div>

        <div class = "col"></div>
    </div>
</div>
{% endblock %}

insta/photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}