mysite/kilogram/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
app_name = 'kilogram'

urlpatterns = [
	url(r'^$', views.IndexView.as_view(),name = 'index'),
]#Generic view사용 (function view대신)
from django.contrib.auth.decorators import login_required
urlpatterns += [
	url(r'^profile/(?P<pk>[0-9]+)/$', login_required(views.ProfileView.as_view()), name = 'profile'),
	url(r'^profile_update/$', login_required(views.ProfileUpdateView.as_view()), name = 'profile_update'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from kilogram import views as kilogram_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$',kilogram_views.IndexView.as_view(), name = 'root'),
    path('admin/', admin.site.urls),
    url(r'^kilogram/', include('kilogram.urls')),
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'^accounts/signup$', kilogram_views.CreateUserView.as_view(), name ="signup"),
	url(r'^accounts/signup/done$', kilogram_views.RegisteredView.as_view(), name = "create_user_done"),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)	#정적으로 추가할 URL = MEDIA_URL이고 실제는 settings.MEIDA_ROOT에 있다

mysite/kilogram/models.py
from django.db import models

# Create your models here.
from django.conf import settings	#photo model

def user_path(instance, filename):	#instance 는 photo 객체, filename = filename
	from random import choice	#string으로 나온 결과에서 하나의 문자열만 뽑기
	import string
	arr = [choice(string.ascii_letters)for _ in range(8)]	#무작위8자
	pid = ''.join(arr)	#파일아이디 생성
	extension = filename.split('.')[-1]	#파일이름에서 확장자 가져오기
	return '%s/%s.%s' %(instance.owner.username, pid, extension)

class Photo(models.Model):
	image = models.ImageField(upload_to = user_path)	#업로드 위치 정함
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE,)	#1:N관계
	thumbnail_image = models.ImageField(blank=True)	#form입력 (선택)
	comment = models.CharField(max_length = 255)
	pub_date = models.DateTimeField(auto_now_add=True)	#자동 생성

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE,)	#현계정의 사용자
	nickname = models.CharField(max_length = 64)
	profile_photo = models.ImageField(blank=True)

mysite/kilogram/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from .form import CreateUserForm
from django.urls import reverse_lazy

# Create your views here.
class IndexView(TemplateView):#Generic TemplateView only used in views that only shows template
	template_name = 'kilogram/index.html'

class CreateUserView(CreateView):
	template_name = 'registration/signup.html'
	#form_class = UserCreationForm
	form_class = CreateUserForm
	success_url = reverse_lazy('create_user_done')

class RegisteredView(TemplateView):
	template_name = 'registration/signup_done.html'

from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
class ProfileView(DetailView):
	context_object_name = 'profile_user'
	model = User
	template_name = 'kilogram/profile.html'

from django.views import View
from .form import UserForm, ProfileForm

class ProfileUpdateView(View): # 간단한 View클래스를 상속 받았으므로 get함수와 post함수를 각각 만들어줘야한다.
    # 프로필 편집에서 보여주기위한 get 메소드
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)  # 로그인중인 사용자 객체를 얻어옴
        user_form = UserForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
        })

        if hasattr(user, 'profile'):  # user가 profile을 가지고 있으면 True, 없으면 False (회원가입을 한다고 profile을 가지고 있진 않으므로)
            profile = user.profile
            profile_form = ProfileForm(initial={
                'nickname': profile.nickname,
                'profile_photo': profile.profile_photo,
            })
        else:
            profile_form = ProfileForm()

        return render(request, 'kilogram/profile_update.html', {"user_form": user_form, "profile_form": profile_form})

    # 프로필 편집에서 실제 수정(저장) 버튼을 눌렀을 때 넘겨받은 데이터를 저장하는 post 메소드
    def post(self, request):
        u = User.objects.get(id=request.user.pk)        # 로그인중인 사용자 객체를 얻어옴
        user_form = UserForm(request.POST, instance=u)  # 기존의 것의 업데이트하는 것 이므로 기존의 인스턴스를 넘겨줘야한다. 기존의 것을 가져와 수정하는 것

        # User 폼
        if user_form.is_valid():
            user_form.save()

        if hasattr(u, 'profile'):
            profile = u.profile
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile) # 기존의 것 가져와 수정하는 것
        else:
            profile_form = ProfileForm(request.POST, request.FILES) # 새로 만드는 것

        # Profile 폼
        if profile_form.is_valid():
            profile = profile_form.save(commit=False) # 기존의 것을 가져와 수정하는 경우가 아닌 새로 만든 경우 user를 지정해줘야 하므로
            profile.user = u
            profile.save()

        return redirect('kilogram:profile', pk=request.user.pk) # 수정된 화면 보여주기

mysite/kilogram/templates/kilogram/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>InstaPage</title>

  <!-- Bootstrap -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'kilogram/style.css' %}" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'kilogram:index' %}"> <span class="glyphicon glyphicon-camera"> </span> InstaPage </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_active %}
        <li><a href="{% url 'kilogram:profile' user.pk %}"> <span class="glyphicon glyphicon-heart"></span> Profile</a></li>
        <li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-heart"></span> {{user.username}}</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-user"></span> Login</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

mysite/kilogram/templates/kilogram/index.html
{% extends 'kilogram/base.html' %}
{% block content %}

<h1>InstaPage Main Page</h1>

{% endblock %}

mysite/kilogram/templates/kilogram/profile.html
{% extends 'kilogram/base.html' %}
{% block content %}

{% load static %}

<div class="row">
    <div class="col-xs-6 col-md-3">
        {% if profile_user.profile.profile_photo %}
        <img class="round" src="{{profile_user.profile.profile_photo.url}}" width="200"> <br>
        {% else %}
        <img class="round" src="{% static 'kilogram/images/default_profile.png' %}" width="200"> <br>
        {% endif %}
    </div>

    <div class="col-xs-6 col-md-3">
        {% if profile_user.profile.nickname %}
        <h2>{{profile_user.profile.nickname}}</h2>
        {% endif %}
        {% if user == profile_user %}   <!-- 로그인한 사용자와 profile_user(프로필 소유자)가 일치할 때만 프로필 편집이 가능하도록 함 -->
        <a href="{% url 'kilogram:profile_update' %}">
            <button type="button" class="btn btn-default">Edit Profile</button></a></h2>
        {% endif %}
        <h3> username: {{profile_user.username}} <br>
            {% if profile_user.first_name is not None %}
            name: {{profile_user.first_name}} {{profile_user.last_name}} <br>
            {% endif %}
        </h3>
    </div>
</div>

{% endblock %}

mysite/kilogram/templates/kilogram/profile_update.html
{% extends 'kilogram/base.html' %}
{% block content %}

<h1>{{user.username}} Profile Update</h1>

    {% if error_msg %}
    <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Error</strong> {{error_msg}}
    </div>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Update" />
    </form>
</p>

{% endblock %}